##
# @file
#
# Travis script for vli
#
# @author Elena Rosinskaya 
#

sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libboost-all-dev
    - libpng14-0
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
notifications:
  email:
    recipients:
      - lrosinskaya@gmail.com
    on_success: change
    on_failure: always
